name: GitlabSync

on:
  - push
  - delete

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wangchucheng/git-repo-sync@v0.1.0
      with:
        target-url: ${{ https://gitlab.com/ivanmoracho/prueba11 }}
        target-username: ${{ gitlab+deploy-token-1324979 }}
        target-token: ${{ 4HHFsKfV6WnT-4Jw7ugf }}
